baseURL = 'https://leafcruncher.com/'
languageCode = 'en-us'
title = 'LEAFCRUNCHER'
theme = 'whiteplain'

copyright = "&copy; COPYRIGHT 2014"

[params]
  google_fonts = [
    ["Noto Sans Mono", "200, 400, 600"],
    ["Fredoka One", "400"]
  ]

  heading_font = "Fredoka One"
  body_font = "Noto Sans Mono"

[params.author]
  name = "ant"
  twitter = "buoydontfloat"
  instagram = "leaf.cruncher"
  github = "79"
  vimeo = "buoydontfloat"
  email = "human@buoydontfloat.com"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Header Menu
[[menu.main]]
  name = "Projects"
  identifier = "projects"
  url = "/projects/"
  weight = 1
[[menu.main]]
  name = "Laboratory"
  identifier = "laboratory"
  url = "/laboratory/"
  weight = 2
[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 3
[[menu.main]]
  name = "Archives"
  identifier = "archives"
  url = "/archives/"
  weight = 4

# Footer Menu
[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"
